import java.sql.*;
import javax.swing.*;

public class CustomerHome extends javax.swing.JFrame {
    Connection con = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    static String jc, jb;
    
    
    /**
     * Creates new form CustomerHome
     */
    public CustomerHome() {
        initComponents();
        setLocation(340, 100);
        setResizable(false);
        String a = SignIn.un;
        
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/group_11", "root", "");
            String query1="select NAME from user where USERNAME='"+a+"'";
            ps = con.prepareStatement(query1);
            rs = ps.executeQuery(query1);
            while(rs.next())
            {
                jLabel2.setText(rs.getString("NAME"));
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        try
        {
            con = DriverManager.getConnection("jdbc:mysql://localhost/group_11","root","");
            String query="SELECT DISTINCT Port_ID FROM excursion_info";
            ps = con.prepareStatement(query);
            rs=ps.executeQuery(query);

            while (rs.next()) 
            {
                select_port.addItem(rs.getString("Port_ID"));
            }
                        
            con.close();
        }
        catch (SQLException e) 
        {
            e.printStackTrace();
        } 
        
    
}
//
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnMyBookings = new javax.swing.JButton();
        btnWaitList = new javax.swing.JButton();
        select_port = new javax.swing.JComboBox<>();
        select_excursion = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        btnMyProfile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        btnMyBookings.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMyBookings.setText("My Bookings");
        btnMyBookings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyBookingsActionPerformed(evt);
            }
        });
        jPanel1.add(btnMyBookings);
        btnMyBookings.setBounds(10, 90, 113, 23);

        btnWaitList.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnWaitList.setText("View Waiting List");
        btnWaitList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWaitListActionPerformed(evt);
            }
        });
        jPanel1.add(btnWaitList);
        btnWaitList.setBounds(130, 90, 139, 23);

        select_port.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        select_port.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Port Number" }));
        select_port.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_portActionPerformed(evt);
            }
        });
        jPanel1.add(select_port);
        select_port.setBounds(20, 200, 160, 21);

        select_excursion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        select_excursion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Excursion" }));
        select_excursion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_excursionActionPerformed(evt);
            }
        });
        jPanel1.add(select_excursion);
        select_excursion.setBounds(190, 200, 310, 21);

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearch);
        btnSearch.setBounds(420, 290, 78, 23);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cruise Excursion Booking System");
        jLabel1.setMaximumSize(new java.awt.Dimension(950, 22));
        jLabel1.setMinimumSize(new java.awt.Dimension(950, 22));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 470, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" Select Port Number");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 170, 220, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(" Select Excursion");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(190, 170, 210, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(360, 50, 140, 20);

        btnLogOut.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogOut);
        btnLogOut.setBounds(420, 90, 83, 23);

        btnMyProfile.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMyProfile.setText("My Profile");
        btnMyProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyProfileActionPerformed(evt);
            }
        });
        jPanel1.add(btnMyProfile);
        btnMyProfile.setBounds(280, 90, 100, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnMyBookingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyBookingsActionPerformed
        CustomerMyBooking Book = new CustomerMyBooking();
        Book.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnMyBookingsActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        jb = (String) select_excursion.getSelectedItem();

        MakeBooking s1 = new MakeBooking();
        s1.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void select_excursionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_excursionActionPerformed
      
    }//GEN-LAST:event_select_excursionActionPerformed

    private void select_portActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_portActionPerformed

        placeInfo();
    }//GEN-LAST:event_select_portActionPerformed

    private void btnWaitListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWaitListActionPerformed
        WaitingList wl = new WaitingList();
        wl.setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnWaitListActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        SignIn sin = new SignIn();
        sin.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnMyProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyProfileActionPerformed
        MyProfile mp = new MyProfile();
        mp.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnMyProfileActionPerformed

    private void placeInfo()
    {
        jc = (String) select_port.getSelectedItem();
        try
        {
            String a1 = jc;
                        //System.out.println(a1);
            //ArrayList<String> name=new ArrayList<String>(); 
            con = DriverManager.getConnection("jdbc:mysql://localhost/group_11","root","");
            String query=("SELECT Excursion_Name FROM excursion_info WHERE Port_ID=?" );
            ps = con.prepareStatement(query);
            ps.setString(1,a1);
            rs=ps.executeQuery();
            //String excursion[]=null;
            select_excursion.removeAllItems();    
            while (rs.next()) 
            {
                select_excursion.addItem(rs.getString("Excursion_Name"));
                //String pat = rs.getString("Excursion_Name");
                //portId=pat.split("");

                //name.add(pat);
                                   //for (int i=0; i<name.size();i++)
                                    //System.out.println(name.get(i));



            }
            //name.add("Excursion name selected");
            //excursion=name.toArray(new String [name.size()]);

            
            con.close();
                       // for (int i=0; i<port.size();i++)

                        //System.out.println(port.get(i));
        }

        catch (SQLException e) 
        {

            e.printStackTrace();
        }
        //jb = (String) jc2.getSelectedItem(); 
                        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
            /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnMyBookings;
    private javax.swing.JButton btnMyProfile;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnWaitList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> select_excursion;
    private javax.swing.JComboBox<String> select_port;
    // End of variables declaration//GEN-END:variables
}
