import javax.swing.*;
import java.sql.*;
//import java.text.SimpleDateFormat;

public class MakeBooking extends javax.swing.JFrame {
    Connection con = null;
    PreparedStatement ps = null;
    CallableStatement cm = null;
    ResultSet rs = null;
    String en = CustomerHome.jb;
    String pn = CustomerHome.jc;
    String a = SignIn.un;

    public MakeBooking() {
        initComponents();
        setLocation(340, 100);
        setResizable(false);
        try
        {
            con = DriverManager.getConnection("jdbc:mysql://localhost/group_11", "root", "");
            String query = "select SUM(No_of_Seats) from booking_info where Booking_Status = 'Booked' AND Excursion_Name='"+en+"'";
            ps = con.prepareStatement(query);
            rs = ps.executeQuery();
            int s = 0;
            while(rs.next())
            {    
                //System.out.println( rs.getInt(1));
                s = rs.getInt(1);
            }
            int available_seats = (32 - s);
            String av_seats = "" + available_seats;
            //System.out.println(available_seats);
            jLabel4.setText(av_seats);
        }
        catch(Exception e)
        {
        }
        
        
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/group_11", "root", "");
            String query1="select NAME from user where USERNAME='"+a+"'";
            ps = con.prepareStatement(query1);
            rs = ps.executeQuery(query1);
            //jLabel2.setText(a);
//            jc1.removeAllItems();
            while(rs.next())
            {
                jLabel10.setText(rs.getString("NAME"));
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
//        String pn = CustomerHome.jc;
//        String en = CustomerHome.jb;
        jLabel2.setText(pn);
        jLabel9.setText(en);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnRequestBook = new javax.swing.JButton();
        no_of_seats = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cruise Excursion Booking System");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 20, 450, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Port");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 140, 120, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Available Seats: ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 190, 130, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Number Of Seats: ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 220, 128, 20);

        btnRequestBook.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRequestBook.setText("Request Booking");
        btnRequestBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestBookActionPerformed(evt);
            }
        });
        jPanel1.add(btnRequestBook);
        btnRequestBook.setBounds(310, 290, 151, 25);

        no_of_seats.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32" }));
        no_of_seats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_of_seatsActionPerformed(evt);
            }
        });
        jPanel1.add(no_of_seats);
        no_of_seats.setBounds(160, 220, 60, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Excursion");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(150, 140, 290, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Name");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(330, 50, 130, 15);

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack);
        btnBack.setBounds(20, 70, 65, 25);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Port");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(20, 110, 50, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Excursion Name");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(150, 110, 110, 20);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(160, 190, 70, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestBookActionPerformed
       
        //int i = 9;
        try
        {
            con = DriverManager.getConnection("jdbc:mysql://localhost/group_11", "root", "");
            String query5="select* from booking_info";// where Booked_By='"+a+"'";
            ps = con.prepareStatement(query5);
            rs = ps.executeQuery();
            if(rs.next())
            {
                String ename = rs.getString(2);
                //System.out.println(ename);
                String bb = rs.getString(7);
                //System.out.println(bb);
                if((jLabel9.getText()).equals(ename) && (jLabel10.getText()).equals(bb))
                {
                    JOptionPane.showMessageDialog(null, "Your have already booked this excursion.");
                }
                else
                {
                    String query="insert into booking_info(Excursion_Name, Port_ID, Booked_Date, No_of_Seats, Booking_Status, Booked_By)"+"values(?,?,current_timestamp,?,?,?)";
                    ps = con.prepareStatement(query);
                    int ns = (Integer.parseInt((String) no_of_seats.getSelectedItem()));
                    if(ns<=(Integer.parseInt(jLabel4.getText())))
                    {   
                        ps.setString(1, jLabel9.getText());
                        ps.setString(2, jLabel2.getText());
                        ps.setInt(3, ns);
                        ps.setString(4, "Booked");
                        ps.setString(5, jLabel10.getText());
                        ps.executeUpdate();
                        JOptionPane.showMessageDialog(null, "Your booking was successful.");
                        ps.addBatch();
                    }
                    else
                    {
                        ps.setString(1, jLabel9.getText());
                        ps.setString(2, jLabel2.getText());
                        ps.setInt(3, ns);
                        ps.setString(4, "Wait Listed");
                        ps.setString(5, jLabel10.getText());
                        ps.executeUpdate();
                        JOptionPane.showMessageDialog(null, "Your booking has been added to the 'Waiting List' due to the unavailability of sufficient seats.");
                        ps.addBatch();
                    }
                }
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);//"You have already booked this excursion.");
            //e.printStackTrace();
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnRequestBookActionPerformed

    private void no_of_seatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_of_seatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no_of_seatsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        CustomerHome ch = new CustomerHome();
        ch.setVisible(true); 
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MakeBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MakeBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MakeBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MakeBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MakeBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRequestBook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> no_of_seats;
    // End of variables declaration//GEN-END:variables
}
